### PR TITLE
Improved issue template

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by agaida** [comment]
@ALL - what do you think?

**Comment by tsujan** [comment]
I think the shorter it is, the more likely it'll be read:
```
<!--- BEFORE FILLING OUT THIS REPORT FORM:                                 --->
<!--- Dear users of stable and LTS (long term service) distributions:      --->
<!--- Please do not file bugs against old (dead) versions but use your     --->
<!--- distribution bugtracker instead. This is esp. true for Ubuntu LTS.   --->
```

**Comment by agaida** [comment]
just change it - fully agree

**Comment by tsujan** [comment]
Other things are good, IMO. I hope this will filter out useless reports and we'll receive real ones more often.

**Comment by agaida** [comment]
@tsujan - you should be able to change the PR

**Comment by tsujan** [comment]
OK. Will only insert the shorter version of LTS warning.

**Comment by tsujan** [comment]
Done.

**Comment by agaida** [comment]
the boring part comes here: https://github.com/lxqt/lxqt/issues/1693

**Pull request merged**
